# Site settings
title: otter.pro
email: dan@otter.pro
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Daniel D Kim and I'm a software developer in the Bay Area.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
url: "" # the base hostname & protocol for your site
#twitter_username: kiwipop
github_username:  otterpro

# permalink is set to /title/, as it works best with NVTool
permalink: /:title/

#TODO: uncomment these on production
#sass:
#    style: :compressed

#jekyll server setting (optional)
# port: 80
host: 0.0.0.0

# pagination
paginate: 2
paginate_path: "/index:num/"

# Build settings
markdown: kramdown

# defaults
defaults:
  -
    scope:
        path: ""
        type: "posts"
    values:
        layout: "post"
        author: "Daniel Kim"
  -
    scope:
        path: ""
        type: "pages"
    values:
        layout: "page"
        author: "Daniel Kim"

# TOC Generator setting
contentsLabel: "Table of Contents"
minItemsToShowToc: 2

# Custom Vars for Apricot Theme

# header banner image file, found in /img/ directory
header_img:  header_book1.jpg

# TODO: maybe?
#number_of_column: 1 
# either 1 or 2 at this time. Default: 1
