# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
url: "" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# permalink is set to /title/, as it works best with NVTool
permalink: /:title/

# pagination
paginate: 2
paginate_path: "/index:num/"

# Build settings
markdown: kramdown


# defaults
defaults:
  -
    scope:
        path: ""
        type: "posts"
    values:
        layout: "post"
        author: "Daniel Kim"
  -
    scope:
        path: ""
        type: "pages"
    values:
        layout: "page"
        author: "Daniel Kim"

# Custom Vars for Apricot Theme
#
